services:
  database:
    image: postgres:16-alpine
    container_name: quize-postgres
    environment:
      POSTGRES_DB: quize
      POSTGRES_PASSWORD: quize
      POSTGRES_USER: quize
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    restart: always


  app:
    container_name: quize-app
    build: .
    environment:
      DATABASE_URL: "postgresql://quize:quize@database:5432/quize?serverVersion=16&charset=utf8"
    networks:
      - quize
    volumes:
      - ./bin:/application/bin
      - ./config:/application/config
      - ./public:/application/public
      - ./src:/application/src
    depends_on:
      - database
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: quize-redis
    networks:
      - quize
    volumes:
      - quize-redis:/data
    restart: always

  webserver:
    image: nginx:alpine
    container_name: quize-webserver
    working_dir: /application
    networks:
      - quize
    volumes:
      - .:/application
      - ./docker/nginx-config/default.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8085:80"

volumes:
  postgres_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  quize-redis:
networks:
  quize:
