services:
  quize-postgres:
    image: postgres:16-alpine
    container_name: quize-postgres
    environment:
      POSTGRES_DB: quize
      POSTGRES_PASSWORD: quize
      POSTGRES_USER: quize
    networks:
      - quize
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    restart: always
    ports:
      - "5434:5432"

  app:
    container_name: quize-app
    build: .
    environment:
      DATABASE_URL: "postgresql://quize:quize@quize-postgres:5432/quize?serverVersion=16&charset=utf8"
      PHP_IDE_CONFIG: "serverName=quize"
      SERVER_URL: "http://127.0.0.1:8085"
    networks:
      - quize
    volumes:
      - .:/application
    depends_on:
      - quize-postgres
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: quize-redis
    networks:
      - quize
    volumes:
      - quize-redis:/data
    restart: always

  webserver:
    image: nginx:alpine
    container_name: quize-webserver
    working_dir: /application
    networks:
      - quize
    volumes:
      - .:/application
      - ./docker/nginx-config/default.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8085:80"

volumes:
  postgres_data:
  quize-redis:

networks:
  quize:
